version: '2'
services:
    erp-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/erp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=erp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
